list: $/winter/sitesearch/models/querylog/columns.yaml
modelClass: Winter\SiteSearch\Models\QueryLog
title: winter.sitesearch::lang.log.title
recordUrl: winter/sitesearch/querylogs/update/:id
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 20
showPageNumbers: true
filter: config_filter.yaml
showSetup: true
showSorting: true
showCheckboxes: true
defaultSort:
    column: created_at
    direction: desc
toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt
