# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: skripteria.sitesearch::lang.log.title

# Model Form Field configuration
form: $/skripteria/sitesearch/models/querylog/fields.yaml

# Model Class name
modelClass: Skripteria\Sitesearch\Models\QueryLog

# Default redirect location
defaultRedirect: skripteria/sitesearch/querylogs

# Update page
update:
    title: skripteria.sitesearch::lang.log.title_update
    redirect: skripteria/sitesearch/querylogs
    redirectClose: skripteria/sitesearch/querylogs
