# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: winter.sitesearch::lang.log.title

# Model Form Field configuration
form: $/winter/sitesearch/models/querylog/fields.yaml

# Model Class name
modelClass: Winter\SiteSearch\Models\QueryLog

# Default redirect location
defaultRedirect: winter/sitesearch/querylogs

# Update page
update:
    title: winter.sitesearch::lang.log.title_update
    redirect: winter/sitesearch/querylogs
    redirectClose: winter/sitesearch/querylogs
